name: traiteur_management
description: A catering management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  # Form validation
  email_validator: ^2.1.17
  url_launcher: ^6.3.2
  fl_chart: ^1.0.0
  table_calendar: 3.1.3
  mockito: ^5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/