name: traiteur_management
description: A catering management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  # Form validation
  email_validator: ^2.1.17
  url_launcher: ^6.3.2
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  mockito: ^5.5.0
  shared_preferences: ^2.5.3
  flutter_localization: ^0.3.3
  currency_formatter: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^11.0.1
  image: ^4.1.3  # optional, for image processing
  path_provider: ^2.1.1  # optional, for file management
  rename_app: ^1.6.5
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  http: ^1.1.0
  googleapis_auth: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true # Or true to generate all Android icons
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your single icon file
  min_sdk_android: 23 # Optional, set your min SDK if needed
  remove_alpha_ios: true # Optional, removes the alpha channel for iOS
  # adaptive_icon_foreground: "assets/icon/foreground.png" # For adaptive icons
  # adaptive_icon_background: "#FFFFFF" # For adaptive icons