// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFekRvH0YL4hKxOwwsjTar4OeN6wWcMpE',
    appId: '1:707485444506:web:9555a169f1e780bd6c3223',
    messagingSenderId: '707485444506',
    projectId: 'traiteurmanagement-bdd43',
    authDomain: 'traiteurmanagement-bdd43.firebaseapp.com',
    storageBucket: 'traiteurmanagement-bdd43.firebasestorage.app',
    measurementId: 'G-PN0W8T0FGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRi-t4NSQzRhtHcEWLddLMPRNjmgEbIu8',
    appId: '1:707485444506:android:1ef981e0bb6c06866c3223',
    messagingSenderId: '707485444506',
    projectId: 'traiteurmanagement-bdd43',
    storageBucket: 'traiteurmanagement-bdd43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-hb1aHRJSCyYTmHX1DKT7fkY4-McL9E',
    appId: '1:707485444506:ios:1fc111c4fdaf83a86c3223',
    messagingSenderId: '707485444506',
    projectId: 'traiteurmanagement-bdd43',
    storageBucket: 'traiteurmanagement-bdd43.firebasestorage.app',
    iosBundleId: 'com.example.traiteurManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-hb1aHRJSCyYTmHX1DKT7fkY4-McL9E',
    appId: '1:707485444506:ios:1fc111c4fdaf83a86c3223',
    messagingSenderId: '707485444506',
    projectId: 'traiteurmanagement-bdd43',
    storageBucket: 'traiteurmanagement-bdd43.firebasestorage.app',
    iosBundleId: 'com.example.traiteurManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFekRvH0YL4hKxOwwsjTar4OeN6wWcMpE',
    appId: '1:707485444506:web:9f0835301400d79c6c3223',
    messagingSenderId: '707485444506',
    projectId: 'traiteurmanagement-bdd43',
    authDomain: 'traiteurmanagement-bdd43.firebaseapp.com',
    storageBucket: 'traiteurmanagement-bdd43.firebasestorage.app',
    measurementId: 'G-RW7MRNY2X6',
  );
}
